// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417135239_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(3913),
                            PasswordHash = "$2a$11$pJv3y.ac.7yL30S27a3BKeQpAc6W2oQNthYM8c8pleP3gdJNFWiHu",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(3920),
                            PasswordHash = "$2a$11$WwnZNU.xTPqLlG2IA4vWE.KcnfzpTf6SIdmRxShy2LJA71OPFbJoe",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4296),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "saivikasreddy.b@gmail.com",
                            FirstName = "Sai Vikas Reddy",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Badam",
                            Phone = "9876543210",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4297)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4300),
                            Department = "Marketing",
                            Designation = "Marketing Executive",
                            Email = "mohith.k@gmail.com",
                            FirstName = "Mohith",
                            JoinDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kankanala",
                            Phone = "9123456780",
                            Salary = 610000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4301)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4305),
                            Department = "HR",
                            Designation = "HR Manager",
                            Email = "sandeep.k@gmail.com",
                            FirstName = "Sandeep",
                            JoinDate = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Konda",
                            Phone = "9876512340",
                            Salary = 720000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4305)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4310),
                            Department = "Finance",
                            Designation = "Senior Accountant",
                            Email = "vineeth.g@gmail.com",
                            FirstName = "Vineeth",
                            JoinDate = new DateTime(2020, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gontla",
                            Phone = "9988776655",
                            Salary = 760000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4310)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4312),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "santosh.s@gmail.com",
                            FirstName = "Santosh",
                            JoinDate = new DateTime(2017, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sane",
                            Phone = "9123123123",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4312)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4315),
                            Department = "Engineering",
                            Designation = "Software Developer",
                            Email = "manohar.g@gmail.com",
                            FirstName = "Manohar",
                            JoinDate = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gundu",
                            Phone = "8456739021",
                            Salary = 1150000m,
                            Status = "InActive",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4315)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4317),
                            Department = "Operations",
                            Designation = "Operations Executive",
                            Email = "sarayu.s@gmail.com",
                            FirstName = "Sarayu",
                            JoinDate = new DateTime(2018, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sigatapu",
                            Phone = "6301832568",
                            Salary = 650000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4318)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4320),
                            Department = "Engineering",
                            Designation = "Associate Software Engineer",
                            Email = "vignesh.g@gmail.com",
                            FirstName = "Vignesh",
                            JoinDate = new DateTime(2021, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gontla",
                            Phone = "9076438215",
                            Salary = 1000000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4320)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4322),
                            Department = "Operations",
                            Designation = "Operations Executive",
                            Email = "rohith.k@gmail.com",
                            FirstName = "Rohith",
                            JoinDate = new DateTime(2023, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "kallepalli",
                            Phone = "9703467210",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4323)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4325),
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "saleem.s@gmail.com",
                            FirstName = "Saleem",
                            JoinDate = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaik",
                            Phone = "8075239416",
                            Salary = 860000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4325)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4327),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "venkatesh.n@gmail.com",
                            FirstName = "Venkatesh",
                            JoinDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Namasani",
                            Phone = "7672398451",
                            Salary = 620000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4328)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4330),
                            Department = "Marketing",
                            Designation = "Marketing Manager",
                            Email = "pradeep.ch@gmail.com",
                            FirstName = "Pradeep",
                            JoinDate = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cheekati",
                            Phone = "8934021786",
                            Salary = 900000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4330)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4332),
                            Department = "Engineering",
                            Designation = "App Developer",
                            Email = "tharun.p@gmail.com",
                            FirstName = "Tharun",
                            JoinDate = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Putta",
                            Phone = "9803672482",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4332)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4334),
                            Department = "Engineering",
                            Designation = "Advance Associate Software Engineer",
                            Email = "vamsi.b@gmail.com",
                            FirstName = "Vamsi",
                            JoinDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Badam",
                            Phone = "7285634021",
                            Salary = 1100000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4358)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4360),
                            Department = "Marketing",
                            Designation = "marketing Manager",
                            Email = "rahul.s@gmail.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sura",
                            Phone = "8356012987",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 13, 52, 37, 600, DateTimeKind.Utc).AddTicks(4360)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
